### ISSUE TITLE
carma-vehicle-model-framework sonar is failing

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#2361]
### Summary

https://github.com/usdot-fhwa-stol/carma-vehicle-model-framework/actions/runs/8623329483/job/23723060265?pr=66
```
Run usdot-fhwa-stol/actions/sonar-scanner@main
Run INIT_ENV="/home/carma/.base-image/init-env.sh"
/opt/sonarqube/sonar-scanner/bin//sonar-scanner
18:50:36.929 INFO: Scanner configuration file: /opt/sonarqube/sonar-scanner/conf/sonar-scanner.properties
18:50:36.939 INFO: Project root configuration file: /opt/carma/src/carma-vehicle-model-framework/.sonarqube/sonar-scanner.properties
18:50:36.968 INFO: SonarScanner 5.0.1.3006
18:50:36.968 INFO: Java 17.0.7 Eclipse Adoptium (64-bit)
18:50:36.968 INFO: Linux 6.5.0-1017-azure amd64
18:50:37.080 DEBUG: keyStore is : 
18:50:37.080 DEBUG: keyStore type is : pkcs12
18:50:37.080 DEBUG: keyStore provider is : 
18:50:37.081 DEBUG: init keystore
18:50:37.081 DEBUG: init keymanager of type SunX509
18:50:37.166 DEBUG: Create: /root/.sonar/cache
18:50:37.166 INFO: User cache: /root/.sonar/cache
18:50:37.167 DEBUG: Create: /root/.sonar/cache/_tmp
18:50:37.169 DEBUG: Extract sonar-scanner-api-batch in temp...
18:50:37.174 DEBUG: Get bootstrap index...
18:50:37.174 DEBUG: Download: https://sonarcloud.io/batch/index
18:50:37.822 DEBUG: Get bootstrap completed
18:50:37.824 DEBUG: Download https://sonarcloud.io/batch/file?name=scanner-sonarcloud-8.0.0.53773-all.jar to /root/.sonar/cache/_tmp/fileCache11491906667972948797.tmp
18:50:44.142 DEBUG: Create isolated classloader...
18:50:44.150 DEBUG: Start temp cleaning...
18:50:44.151 DEBUG: Temp cleaning done
18:50:44.152 INFO: Analyzing on SonarCloud
18:50:44.152 INFO: Default locale: "en_US", source code encoding: "US-ASCII" (analysis is platform dependent)
18:50:44.152 DEBUG: Work directory: /opt/carma/src/carma-vehicle-model-framework/.scannerwork
18:50:44.153 DEBUG: Execution execute
18:50:44.314 DEBUG: Scanner max available memory: 4190109696
18:50:44.321 DEBUG: SonarCloud 10.6.0.2114
18:50:44.457 INFO: Load global settings
18:50:44.977 DEBUG: GET 200 https://sonarcloud.io/api/settings/values.protobuf | time=517ms
18:50:44.984 INFO: Load global settings (done) | time=527ms
18:50:44.987 INFO: Server id: 1BD809FA-AWHW8ct9-T_TB3XqouNu
18:50:44.992 DEBUG: Create : /root/.sonar/_tmp
18:50:44.993 INFO: User cache: /root/.sonar/cache
18:50:44.998 INFO: Loading required plugins
18:50:44.998 INFO: Load plugins index
18:50:45.471 DEBUG: GET 200 https://sonarcloud.io/api/plugins/installed | time=472ms
18:50:45.500 INFO: Load plugins index (done) | time=502ms
18:50:45.500 INFO: Load/download plugins
18:50:45.501 DEBUG: Download plugin 'iac' to '/root/.sonar/_tmp/fileCache12122343554369103510.tmp'
18:50:45.539 DEBUG: GET 200 https://scanner.sonarcloud.io/plugins/iac/versions/b60da79182c30a7f57296503ec4f9971.jar | time=38ms
18:50:45.760 DEBUG: Download plugin 'jacoco' to '/root/.sonar/_tmp/fileCache13021402130880315390.tmp'
18:50:45.774 DEBUG: GET 200 https://scanner.sonarcloud.io/plugins/jacoco/versions/04bba36a445c3713a632aa358be2f99c.jar | time=13ms
18:50:45.777 DEBUG: Download plugin 'license' to '/root/.sonar/_tmp/fileCache2962528046420735968.tmp'
18:50:45.783 DEBUG: GET 200 https://scanner.sonarcloud.io/plugins/license/versions/4d6c61feb3f1f043bfb31af51cdf5830.jar | time=6ms
18:50:45.787 DEBUG: Download plugin 'python' to '/root/.sonar/_tmp/fileCache18101581672288528591.tmp'
18:50:45.795 DEBUG: GET 200 https://scanner.sonarcloud.io/plugins/python/versions/a1f37ca54b6407c29e14d6a84ef527be.jar | time=8ms
18:50:45.933 DEBUG: Download plugin 'text' to '/root/.sonar/_tmp/fileCache1637019327316933676.tmp'
18:50:45.939 DEBUG: GET 200 https://scanner.sonarcloud.io/plugins/text/versions/7c2ce90b3065bfaf5d55dd3ea4deca5e.jar | time=5ms
18:50:45.987 DEBUG: Download plugin 'xml' to '/root/.sonar/_tmp/fileCache4641298941067824676.tmp'
18:50:45.992 DEBUG: GET 200 https://scanner.sonarcloud.io/plugins/xml/versions/dc7530956473c81946456a4a3587ff22.jar | time=5ms
18:50:46.008 INFO: Load/download plugins (done) | time=508ms
18:50:46.008 DEBUG: Plugins not loaded because they are optional: [abap, sonarapex, csharp, cpp, cobol, dbd, dbdjavafrontend, dbdpythonfrontend, flex, go, web, java, javascript, kotlin, php, pli, plsql, rpg, ruby, sonarscala, swift, tsql, vbnet, vb, security, securitycsharpfrontend, securityjsfrontend, securityjavafrontend, securityphpfrontend, securitypythonfrontend]
18:50:46.039 DEBUG: Plugins loaded:
18:50:46.040 DEBUG:   * License for SonarLint 8.0.0.53773 (license)
18:50:46.040 DEBUG:   * Python Code Quality and Security 4.17.0.14845 (python)
18:50:46.040 DEBUG:   * XML Code Quality and Security 2.10.0.4108 (xml)
18:50:46.040 DEBUG:   * JaCoCo 1.3.0.1538 (jacoco)
18:50:46.040 DEBUG:   * IaC Code Quality and Security 1.27.0.9518 (iac)
18:50:46.040 DEBUG:   * Text Code Quality and Security 2.10.0.2188 (text)
18:50:49.199 INFO: Final Memory: 9M/48M
java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.scan.filesystem.InputComponentStore
18:50:49.199 INFO: ------------------------------------------------------------------------
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:52)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.java:1034)
	at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:122)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:125)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:57)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:51)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: java.lang.IllegalStateException: Unable to load component interface org.sonar.scanner.scan.branch.BranchConfiguration
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:52)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:50)
	... 34 more
Caused by: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
```

### Version

4.3.0 (Current)

### Expected Behavior

see above

### Actual Behavior

see above

### Steps to Reproduce the Actual Behavior

see above

**Comment by MishkaMN** [comment]
This repository is also has not been updated for 3 years. Its dependency of sigpack is likely getting removed.
